import turtle

cordefundo = input("pufavo, me diga a cor de fundo ")
cordetortuga = input("pufavo, me diga a cor do bicho ")
larguradetortuga = input("pufavo, me diga o tamain do bicho ")
wn = turtle.Screen()
wn.bgcolor(cordefundo)

alex = turtle.Turtle()
alex.color(cordetortuga)
alex.width(int(larguradetortuga))

alex.forward(50)
alex.left(90)
alex.forward(30)

cordetortuga = input("pufavo, me diga a cor do bicho ")
alex.color(cordetortuga)
alex.forward(50)
alex.left(90)
alex.forward(30)
cordetortuga = input("pufavo, me diga a cor do bicho ")
alex.color(cordetortuga)
alex.forward(50)
alex.left(90)
alex.forward(30)
cordetortuga = input("pufavo, me diga a cor do bicho ")
alex.color(cordetortuga)
alex.forward(50)
alex.left(90)
alex.forward(30)
cordetortuga = input("pufavo, me diga a cor do bicho ")
alex.color(cordetortuga)
alex.forward(50)
alex.left(90)
alex.forward(30)
cordetortuga = input("pufavo, me diga a cor do bicho ")
alex.color(cordetortuga)
alex.forward(50)
alex.left(90)
alex.forward(30)
cordetortuga = input("pufavo, me diga a cor do bicho ")
alex.color(cordetortuga)
alex.forward(50)
alex.left(90)
alex.forward(30)
cordetortuga = input("pufavo, me diga a cor do bicho ")
alex.color(cordetortuga)
alex.forward(50)
alex.left(90)
alex.forward(30)

wn.mainloop()
